#!/bin/bash -f
#filename   ::  G09_Environment
#Author     ::  Igor Ying Zhang, Xin Xu
#Purpose    ::  Setting G09 running environment and run g09
#Usage      ::  G09_Environment G09InpFile
#Version    ::  V1.0(20210514)
#History    ::  V1.0 :: complete the basic functionality

#================================================
# System-dependent setting parameters, which 
# should be defined by the users
#================================================
export g09root=/share/apps/gaussian/G09D01
. $g09root/g09/bsd/g09.profile
if [ ! -d "/scratch/scr/$USER" ]; then
   mkdir /scratch/scr/$USER
fi
export GAUSS_SCRDIR=/scratch/scr/$USER/$LSB_JOBID
if [ ! -d "$GAUSS_SCRDIR" ]; then
   mkdir $GAUSS_SCRDIR
fi
#================================================


#================================================
# No change is required for the rest part
#================================================
TDWDD=$GAUSS_SCRDIR
# get the postfix of the input file
TmpArray=($(echo $1|tr "/" "\n"))
FullName=${TmpArray[-1]}
TmpArray=($(echo $FullName|tr "." "\n"))
PostFix=${TmpArray[-1]}
#echo $PostFix
#echo $FullName

#
if [ $PostFix == 'com' ]||[ $PostFix == 'gjf' ]||[ $PostFix == 'inp' ]; then
    # At first, set the chk file into scratch in the node
    cont=`grep -c "\%chk" $1`
    chkdir=""
    chkname=""
    if [ $cont -eq 0 ]; then
       echo "No %chk statement"
       $g09root/g09/g09 $1
    else
       if [ $cont -gt 1 ]; then
             echo "More than one '%chk' statements"
             echo "Warning :: handle the chk file in the default direction,"
             echo "           which might be on the NFS resulting in increasing the burden of IO dramatically"
             #run g09
             $g09root/g09/g09 $1
       else
             #echo "Only one '%chk' statement"
             chkfile=`grep -i "%chk" $1|cut -f2 -d'='`
             chkname=`echo $chkfile|cut -f2 -d'.'`
             chkroot=`echo $chkfile|cut -f1 -d'.'`
             if [ -e $chkroot.chk ]; then
                 cp $chkroot.chk $TDWDD/
             fi
             #if [ $chkdir == $chkname ]; then
             #    chkdir=""
             #fi
             newchkroot=$TDWDD/$chkroot
             #echo "chkroot is "$chkroot", and newchkroot is "$newchkroot
             ./ChkReplace.py $1 $chkroot $newchkroot
             #run g09
             $g09root/g09/g09 $1
             cp $newchkroot.chk $chkroot.chk
       fi
    fi
else
    if [ $PostFix == 'chk' ]; then
        #formchk chk file
        if [ -e $1 ]; then
            $g09root/g09/formchk $1
        else
            echo "The chk file "$1 "doesn\'t exist"
        fi
    fi
fi
#
#Clean the scratch
rm -rf $TDWDD
